[package]
name = "Noble"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
serenity = "0.12.4"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[profile.release]
#debug = true

[profile.dev.package."*"]
opt-level = 3
